//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ncsibg.usasoftball.com/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name message from namespace http://ncsibg.usasoftball.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ncsibg.usasoftball.com/BGStatus", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.BGStatusResponse BGStatus(ConsoleApp1.ServiceReference1.BGStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ncsibg.usasoftball.com/BGStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.BGStatusResponse> BGStatusAsync(ConsoleApp1.ServiceReference1.BGStatusRequest request);
        
        // CODEGEN: Generating message contract since element name TellFortuneResult from namespace http://ncsibg.usasoftball.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ncsibg.usasoftball.com/TellFortune", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.TellFortuneResponse TellFortune(ConsoleApp1.ServiceReference1.TellFortuneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ncsibg.usasoftball.com/TellFortune", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.TellFortuneResponse> TellFortuneAsync(ConsoleApp1.ServiceReference1.TellFortuneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BGStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BGStatus", Namespace="http://ncsibg.usasoftball.com/", Order=0)]
        public ConsoleApp1.ServiceReference1.BGStatusRequestBody Body;
        
        public BGStatusRequest() {
        }
        
        public BGStatusRequest(ConsoleApp1.ServiceReference1.BGStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ncsibg.usasoftball.com/")]
    public partial class BGStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public BGStatusRequestBody() {
        }
        
        public BGStatusRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BGStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BGStatusResponse", Namespace="http://ncsibg.usasoftball.com/", Order=0)]
        public ConsoleApp1.ServiceReference1.BGStatusResponseBody Body;
        
        public BGStatusResponse() {
        }
        
        public BGStatusResponse(ConsoleApp1.ServiceReference1.BGStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ncsibg.usasoftball.com/")]
    public partial class BGStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BGStatusResult;
        
        public BGStatusResponseBody() {
        }
        
        public BGStatusResponseBody(string BGStatusResult) {
            this.BGStatusResult = BGStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TellFortuneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TellFortune", Namespace="http://ncsibg.usasoftball.com/", Order=0)]
        public ConsoleApp1.ServiceReference1.TellFortuneRequestBody Body;
        
        public TellFortuneRequest() {
        }
        
        public TellFortuneRequest(ConsoleApp1.ServiceReference1.TellFortuneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TellFortuneRequestBody {
        
        public TellFortuneRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TellFortuneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TellFortuneResponse", Namespace="http://ncsibg.usasoftball.com/", Order=0)]
        public ConsoleApp1.ServiceReference1.TellFortuneResponseBody Body;
        
        public TellFortuneResponse() {
        }
        
        public TellFortuneResponse(ConsoleApp1.ServiceReference1.TellFortuneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ncsibg.usasoftball.com/")]
    public partial class TellFortuneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TellFortuneResult;
        
        public TellFortuneResponseBody() {
        }
        
        public TellFortuneResponseBody(string TellFortuneResult) {
            this.TellFortuneResult = TellFortuneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.WebService1Soap>, ConsoleApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.BGStatusResponse ConsoleApp1.ServiceReference1.WebService1Soap.BGStatus(ConsoleApp1.ServiceReference1.BGStatusRequest request) {
            return base.Channel.BGStatus(request);
        }
        
        public string BGStatus(string message) {
            ConsoleApp1.ServiceReference1.BGStatusRequest inValue = new ConsoleApp1.ServiceReference1.BGStatusRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.BGStatusRequestBody();
            inValue.Body.message = message;
            ConsoleApp1.ServiceReference1.BGStatusResponse retVal = ((ConsoleApp1.ServiceReference1.WebService1Soap)(this)).BGStatus(inValue);
            return retVal.Body.BGStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.BGStatusResponse> ConsoleApp1.ServiceReference1.WebService1Soap.BGStatusAsync(ConsoleApp1.ServiceReference1.BGStatusRequest request) {
            return base.Channel.BGStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.BGStatusResponse> BGStatusAsync(string message) {
            ConsoleApp1.ServiceReference1.BGStatusRequest inValue = new ConsoleApp1.ServiceReference1.BGStatusRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.BGStatusRequestBody();
            inValue.Body.message = message;
            return ((ConsoleApp1.ServiceReference1.WebService1Soap)(this)).BGStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.TellFortuneResponse ConsoleApp1.ServiceReference1.WebService1Soap.TellFortune(ConsoleApp1.ServiceReference1.TellFortuneRequest request) {
            return base.Channel.TellFortune(request);
        }
        
        public string TellFortune() {
            ConsoleApp1.ServiceReference1.TellFortuneRequest inValue = new ConsoleApp1.ServiceReference1.TellFortuneRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.TellFortuneRequestBody();
            ConsoleApp1.ServiceReference1.TellFortuneResponse retVal = ((ConsoleApp1.ServiceReference1.WebService1Soap)(this)).TellFortune(inValue);
            return retVal.Body.TellFortuneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.TellFortuneResponse> ConsoleApp1.ServiceReference1.WebService1Soap.TellFortuneAsync(ConsoleApp1.ServiceReference1.TellFortuneRequest request) {
            return base.Channel.TellFortuneAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.TellFortuneResponse> TellFortuneAsync() {
            ConsoleApp1.ServiceReference1.TellFortuneRequest inValue = new ConsoleApp1.ServiceReference1.TellFortuneRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.TellFortuneRequestBody();
            return ((ConsoleApp1.ServiceReference1.WebService1Soap)(this)).TellFortuneAsync(inValue);
        }
    }
}
